package io.github.aquerr.eaglefactions.api.entities;

public enum FactionPermission
{
    INTERACT,
    BLOCK_PLACE,
    BLOCK_DESTROY,
    TERRITORY_CLAIM,
    ATTACK,
    INVITE_PLAYERS,
    VIEW_FACTION_CHEST,
    MANAGE_RANKS,
    MANAGE_INTERNAL_CLAIMS,
    KICK_MEMBERS,
    MANAGE_FACTION_HOME,
    MANAGE_MOTD,
    MANAGE_DESCRIPTION,
    MANAGE_IS_PUBLIC,
    MANAGE_TAG_NAME,
    MANAGE_TAG_COLOR,
    MANAGE_RELATIONS,
    RENAME_FACTION,
    INTERNAL_CLAIM_BYPASS_ACCESS
}
